.PHONY: clean All

All:
	@echo "----------Building project:[ POINTERS - Debug ]----------"
	@"$(MAKE)" -f  "POINTERS.mk"
clean:
	@echo "----------Cleaning project:[ POINTERS - Debug ]----------"
	@"$(MAKE)" -f  "POINTERS.mk" clean
